### ISSUE TITLE
How to change the font size of the editor?

### ISSUE THREAD

**Issue by brendand** [khoi/codemirror-swift#3]
I've been researching the documentation and online examples of how to change the font size, but most of the information I can find is very old and applies to CodeMirror 5. I'm using this package with CodeMirror 6 now but cannot figure out how to provide the ability to dynamically change the font size. I want a font size slider to control the font size.

If I put a `fontSize: 13pt;` item into the `baseTheme` constant then I can see the new font size. But I want to make that dynamic.

Do you know how to do that?

**Comment by khoi** [comment]
https://codemirror.net/examples/config/ 

`Dynamic Configuration` should be a good start
