### ISSUE TITLE
Update to latest CodeMirror 6.x version?

### ISSUE THREAD

**Issue by brendand** [khoi/codemirror-swift#5]
Would it be possible to update CodeMirror to the latest 6.x version? There's a function in there I'm trying to use called `scopeCompletionSource`, but it doesn't seem to be available in this version.

I'm trying to configure autocomplete to trigger when you type in the `.` character and then display a list of context sensitive completions pertaining to the token typed before the `.`

Here's a link to the mention of it:

[https://github.com/codemirror/lang-javascript/#user-content-scopecompletionsource](https://github.com/codemirror/lang-javascript/#user-content-scopecompletionsource)

Thanks!

**Comment by khoi** [comment]
should be relative easy to do, can u submit a PR?

**Comment by brendand** [comment]
That's the thing, I'm not sure how you generated the set of files that you have. I tried installing from `npm`, but it brought in hundreds of packages and things. How did you generate the 44 items that are in your package? Did you grab it from their dev repo? 

Sorry, I'm new to CodeMirror and I've spent hours trying to figure it out, but then kept getting compile errors and such, so I thought I'd ask to see if you could update the package.

Is this a project you're no longer working on? It's the only one that I could find for Swift that had CodeMirror 6 in it. All the others seem to use CodeMirror 5.

**Comment by brendand** [comment]
If you tell me what steps to do, I can submit a PR if you like.

Did you get the files from the CodeMirror dev repo? Or did you use npm install to get them? And how did you get just the modules that are in your version?

**Comment by khoi** [comment]
Hey @brendand 

The subfolder `https://github.com/khoi/codemirror-swift/tree/main/Sources/CodeMirror/src` can be treated like a node project.

See `package.json` for all the modules I used, u can `npm install` or `upgrade` inside that folder 

I think I was just following the instruction on https://codemirror.net/examples/bundle/

**Comment by brendand** [comment]
I actually did manage to find out that just by changing the version numbers in the `package.json` file would update them to the current versions.  At the time I wrote my reply I had no idea how it was all put together. I'm still trying to enhance it to support dynamic font sizing and hopefully context aware snippets. Both are proving to be quite challenging.

**Comment by khoi** [comment]
Yeah, I'd play with codemirror in javascript first before thinking about porting it to Swift.

If there is something useful, please submit a PR, I'd highly appreciate it.

**Comment by khoi** [comment]
it's been updatedin 5edc929
